### ISSUE TITLE
Is this repo still used?

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/OpenOCD-build-script#2]
The latest version in the static branch here is 0.9.0-arduino6-static, but the SAMD core has versions up to 0.10.0-arduino9 (e.g. from http://downloads.arduino.cc/tools/openocd-0.10.0-arduino9-static-i686-ubuntu12.04-linux-gnu.tar.bz2). So is this repo still used? Is there some other place where these builds are tracked? Or did someone forget to push? :-)

@facchinm, I think this might be something you'll know?

**Comment by facchinm** [comment]
Hi @matthijskooijman, thanks for noticing! I was pushing here https://github.com/facchinm/OpenOCD-build-script :sweat_smile: Will push the branch here too and change the jenkins job accordingly

**Comment by facchinm** [comment]
Done https://github.com/arduino/OpenOCD-build-script/pull/3 :wink:

**Comment by matthijskooijman** [comment]
Thanks! TBH, the history is not all that great, but at least it's available now. Some more questions, though:
 - Are there tags for the releases that you haven't pushed yet? If not, would it be good to create them?
 - I see a bunch of versions here, up to 0.10.0-arduino12, but I only see the arduino1, arduino7 and arduino12 in the package json. Are the rest experimental builds?
 - It seems that these builds use OpenOCD from git, rather than the 0.10.0 release version. Maybe that should be reflected in the version? E.g. something like 0.10.0-git0a11537-arduino12? I was a bit surprised that my Arduino-installed OpenOCD had extra features compared to my Debian-isntalled OpenOCD, since both seemed to be 0.10.0.

**Comment by matthijskooijman** [comment]
For the last point, a date-based version might be clearer, e.g. `0.10.0-git20200205-arduino12`.

**Comment by facchinm** [comment]
~Agree, `0.10.0-git20200205-arduino12` looks good indeed, I'll make a PR now~

**Comment by facchinm** [comment]
When launching we already get something like `Open On-Chip Debugger 0.10.0+dev-g0a11537b (2020-02-14-11:41)` , could it be enough information so we can avoid changing the package name?

**Comment by matthijskooijman** [comment]
When I wonder what version a core includes, I would look at the json version information, I might not even have it installed yet. Of course, running openocd to find the version is the best source of truth, but at least *some* indication that it is not just 0.10.0, but > 0.10.0 from git in the version number would IMHO still be meaningful (and then a datestamp might be a good way for that).
